server:
  port: 10010
spring:
  http:
    multipart:
      maxFileSize: 100Mb #解决上传文件过大
      maxRequestSize: 1000Mb
  # dubbo的配置
  dubbo:
    # dubbo中的服务名称
    application: manage-web
    protocol:
      # dubbo的通讯协议名称
      name: dubbo
    registry:
      # zookeeper注册中心的地址
      address: 192.168.182.129:2181
      # zookeeper的通讯协议的名称
      protocol: zookeeper
      # dubbo的服务的扫描路径
    base-package: com.qc
    consumer:
      # 设置超时时间
      timeout: 600000
      # 是否检查服务存在
      consumer: false




##日志级别
#logging:
#  level:
#    root=debug: info

# OSS相关配制
oss:
  file:
    endpoint: http://oss-cn-hangzhou.aliyuncs.com # 阿里云内网或者外网的访问地址
    accessKeyId: LTAIoYnHqdqWr77t # 阿里云控制台获取
    accessKeySecret: iqo7OrXUqEJ6PbzVyC00BAPuMTtVi4 # 阿里云控制台获取
    bucketname: qc-chenyushi #自己定义的块儿名称
   # filehost: blog: # 自己定义的路径名称
